version: "3.9"

services:
  stoa0:
    image: github.com/vontikov/stoa:0.0.1
    container_name: stoa0
    hostname: stoa0
    command: stoa -bootstrap stoa0,stoa1,stoa2
  stoa1:
    image: github.com/vontikov/stoa:0.0.1
    container_name: stoa1
    hostname: stoa1
    command: stoa
  stoa2:
    image: github.com/vontikov/stoa:0.0.1
    container_name: stoa2
    hostname: stoa2
    command: stoa

  master:
    image: github.com/vontikov/pgcluster:0.0.1
    container_name: pg_master
    hostname: pg_master
    environment:
      - PG_CLUSTER_NAME=master
      - PG_SYNC_NAMES=FIRST 1 (replica0)

      - PGCP_LOG_LEVEL=debug
      - PGCP_STORAGE_BOOTSTRAP=stoa0,stoa1,stoa2
    ports:
      - 5432:5432
      - 3501:3501

  replica0:
    image: github.com/vontikov/pgcluster:0.0.1
    container_name: pg_replica0
    hostname: pg_replica0
    environment:
      - PG_CLUSTER_NAME=replica0
      - PG_REPLICATION_MODE=replica
      - PG_REPLICATION_HOST=pg_master

      - PGCP_LOG_LEVEL=debug
      - PGCP_STORAGE_BOOTSTRAP=stoa0,stoa1,stoa2
    ports:
      - 5433:5432
      - 3502:3501

  replica1:
    image: github.com/vontikov/pgcluster:0.0.1
    container_name: pg_replica1
    hostname: pg_replica1
    environment:
      - PG_CLUSTER_NAME=replica1
      - PG_REPLICATION_MODE=replica
      - PG_REPLICATION_HOST=pg_master

      - PGCP_LOG_LEVEL=debug
      - PGCP_STORAGE_BOOTSTRAP=stoa0,stoa1,stoa2
    ports:
      - 5434:5432
      - 3503:3501
